[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
extra_standard_library = ["typing_extensions"]

[tool.black]
target_version = ["py310"]
skip_string_normalization = true

[tool.ruff]
select = ["E", "F", "B"]
ignore = ["B008", "B905"]
